### PR TITLE
Plugin Api

### PR DESCRIPTION
**Pull request by castelbuilder123**
It is not going over network, it works via dll loading of all dlls in "plugins". All classes extending IPlugin will be loaded

### CODE REVIEW

**Comment by FICTURE7** [comment]
Looks like your build is failing at travis-ci.

**Comment by castelbuilder123** [comment]
Note about Travis-CI: It fails at CoCSharp.ClientApi, a empty class library which will contain network api  functionality in the future. on my machine it builds perfectly fine.

**Comment by castelbuilder123** [comment]
This fixed the errors at ClientApi

**Comment by castelbuilder123** [comment]
Build fails because you got code in ingamepackethandler.cs from git and it doesent find my api files:


	CSC: error CS2001: Source file `API/IPlugin.cs' could not be found
	CSC: error CS2001: Source file `API/PluginApi.cs' could not be found
	CSC: error CS2001: Source file `API/PluginLoader.cs' could not be found
	Handlers/InGamePacketHandlers.cs(20): error CS1525: Unexpected symbol `<<'
	Handlers/InGamePacketHandlers.cs(21,19): error CS1525: Unexpected symbol `.'
	Handlers/InGamePacketHandlers.cs(21,66): error CS1525: Unexpected symbol `.'
	Handlers/InGamePacketHandlers.cs(22,94): error CS1525: Unexpected symbol `.'
	Handlers/InGamePacketHandlers.cs(23): error CS1525: Unexpected symbol `=='
	Handlers/InGamePacketHandlers.cs(28): error CS1525: Unexpected symbol `>>'
	Handlers/InGamePacketHandlers.cs(28,9): error CS1525: Unexpected symbol `aaeb47915cb292f939cacb38823ba66d43a87b5'
	Handlers/InGamePacketHandlers.cs(29,13): error CS0128: A local variable named `Console' is already defined in this scope
	Handlers/InGamePacketHandlers.cs(29,19): error CS1525: Unexpected symbol `.'

**Comment by castelbuilder123** [comment]
Now this branch is safe to merge, the travis-ci error comes from InGamePacketHandler.cs, please look at the file

**Comment by FICTURE7** [comment]
Yeah saw it but I was playing around with Visual Studio Code
I fixed it and I think we are going to create a new branch instead and do the changes there.

**Comment by castelbuilder123** [comment]
create it i will create a new pull request

**Comment by FICTURE7** [comment]
Closing

**Comment by FICTURE7** [comment]
I fixed the conflict by the way.

**Comment by castelbuilder123** [comment]
yeah saw it

**Pull request closed without merging**
