### PR TITLE
Added clan search proxying

### PR DESCRIPTION
**Pull request by circa94**
the writer has still no function. will implement it soon and do more stuff

### CODE REVIEW

**Comment by FICTURE7** [comment]
Alright I'll take a look at it before I merge the pull request. :]

**Comment by FICTURE7** [comment]
Am not going to merge any of this stuff, because we are not making a clan search API, if you want to do it, make another project for it. Or you could just make a plugin for this. Its one of the main reason for this.

**Comment by FICTURE7** [comment]
CoCSharp is a library you can use it where ever you want to.

**Comment by circa94** [comment]
Okay sorry... then what else can i do.. there is not much documentated how to use the libary

**Comment by FICTURE7** [comment]
Check the wiki. Thanks for trying to help tho :]

**Comment by FICTURE7** [comment]
Its good to see that people are interested in this thing! ;]

**Comment by FICTURE7** [comment]
Actually maybe we could try to make a UI plugin for the client. I making a new issue for it.

**Comment by FICTURE7** [comment]
See #32

**Comment by circa94** [comment]
seriously? i started a UI for the proxy but i thought you prefere more an oldsql console :D 
But sure, as a plugin it will be great. i'llread the wiki and try to figure out how plugins are working. BTW, ive send you an email

**Comment by FICTURE7** [comment]
Hey can't blame me, terminals and TUIs are sexy. ;]

**Comment by circa94** [comment]
for sure. i love the dark purple color for clan names in the Client :D

**Pull request closed without merging**
